title: Refuting Jehovah's Witnesses
description: Equip yourself with solid arguments to defend the true Christian faith.

baseurl: "/refute-jw" # the subpath of your site, e.g. /blog
url: "https://refute-jw.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_url: https://github.com/vakho10/refute-jw

show_excerpts: true
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag